package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/mmmtmi/excel-template-mapper/graph/model"
	"github.com/mmmtmi/excel-template-mapper/internal/store/mysql"
)

// CreateTemplate is the resolver for the createTemplate field.
func (r *mutationResolver) CreateTemplate(ctx context.Context, input model.CreateTemplateInput) (*model.Template, error) {
	panic(fmt.Errorf("not implemented: CreateTemplate - createTemplate"))
}

// UpdateTemplate is the resolver for the updateTemplate field.
func (r *mutationResolver) UpdateTemplate(ctx context.Context, id string, input model.UpdateTemplateInput) (*model.Template, error) {
	panic(fmt.Errorf("not implemented: UpdateTemplate - updateTemplate"))
}

// CreateRule is the resolver for the createRule field.
func (r *mutationResolver) CreateRule(ctx context.Context, input model.CreateRuleInput) (*model.Rule, error) {
	panic(fmt.Errorf("not implemented: CreateRule - createRule"))
}

// UpdateRule is the resolver for the updateRule field.
func (r *mutationResolver) UpdateRule(ctx context.Context, id string, input model.UpdateRuleInput) (*model.Rule, error) {
	panic(fmt.Errorf("not implemented: UpdateRule - updateRule"))
}

// Templates is the resolver for the templates field.
func (r *queryResolver) Templates(ctx context.Context) ([]*model.Template, error) {
	panic(fmt.Errorf("not implemented: Templates - templates"))
}

// Template is the resolver for the template field.
func (r *queryResolver) Template(ctx context.Context, name string) (*model.Template, error) {

	tpl, err := mysql.GetTemplateByName(ctx, r.DB, name)
	if err != nil {
		return nil, err
	}

	out := &model.Template{
		ID:           tpl.ID,
		Name:         tpl.Name,
		Target:       tpl.Target,
		SheetName:    tpl.SheetName,
		HeaderRow:    int32(tpl.HeaderRow),
		DataStartRow: int32(tpl.DataStartRow),
	}

	return out, err

}

// Rules is the resolver for the rules field.
func (r *queryResolver) Rules(ctx context.Context, templateID string) ([]*model.Rule, error) {
	panic(fmt.Errorf("not implemented: Rules - rules"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
