// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateRuleInput struct {
	TemplateID  string  `json:"templateId"`
	SourceKey   string  `json:"sourceKey"`
	SourceType  string  `json:"sourceType"`
	TargetLabel string  `json:"targetLabel"`
	Transform   *string `json:"transform,omitempty"`
	Required    bool    `json:"required"`
}

type CreateTemplateInput struct {
	Name         string  `json:"name"`
	SheetName    *string `json:"sheetName,omitempty"`
	HeaderRow    int32   `json:"headerRow"`
	DataStartRow int32   `json:"dataStartRow"`
}

type Mutation struct {
}

type Query struct {
}

type Rule struct {
	ID           string  `json:"id"`
	TemplateID   string  `json:"templateId"`
	SourceType   string  `json:"sourceType"`
	SourceKey    string  `json:"sourceKey"`
	TargetID     string  `json:"targetID"`
	TargetLabel  string  `json:"targetLabel"`
	CanonicalKey *string `json:"canonicalKey,omitempty"`
	Transform    *string `json:"transform,omitempty"`
	Required     bool    `json:"required"`
	Priority     *int32  `json:"priority,omitempty"`
	Evidence     *string `json:"evidence,omitempty"`
	CreatedAt    string  `json:"createdAt"`
	UpdatedAt    string  `json:"updatedAt"`
}

type Template struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Target       string  `json:"target"`
	SheetName    *string `json:"sheetName,omitempty"`
	HeaderRow    int32   `json:"headerRow"`
	DataStartRow int32   `json:"dataStartRow"`
	Notes        *string `json:"notes,omitempty"`
	CreatedAt    *string `json:"createdAt,omitempty"`
	UpdatedAt    *string `json:"updatedAt,omitempty"`
}

type UpdateRuleInput struct {
	SourceKey   *string `json:"sourceKey,omitempty"`
	SourceType  *string `json:"sourceType,omitempty"`
	TargetLabel *string `json:"targetLabel,omitempty"`
	Transform   *string `json:"transform,omitempty"`
	Required    *bool   `json:"required,omitempty"`
}

type UpdateTemplateInput struct {
	Name         *string `json:"name,omitempty"`
	SheetName    *string `json:"sheetName,omitempty"`
	HeaderRow    *int32  `json:"headerRow,omitempty"`
	DataStartRow *int32  `json:"dataStartRow,omitempty"`
}
